# Generated by Django 5.2 on 2025-05-15 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
