# Generated by Django 5.2 on 2025-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_days',
            new_name='available_days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
