# Generated by Django 5.2 on 2025-05-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0002_schedule_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_created',
        ),
    ]
