# Generated by Django 5.2 on 2025-05-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0003_remove_schedule_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_days',
            new_name='available_days',
        ),
    ]
