# Generated by Django 5.2 on 2025-05-16 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0004_rename_schedule_days_schedule_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
