# Generated by Django 5.2 on 2025-05-16 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0005_schedule_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
