# Generated by Django 5.2 on 2025-05-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0006_alter_schedule_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
