# Generated by Django 5.2 on 2025-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.CharField(default='sent', max_length=20),
        ),
    ]
