# Generated by Django 5.2 on 2025-06-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
