# Generated by Django 5.2 on 2025-05-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0002_notification_fcm_token_notification_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sent',
            new_name='sent_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
