# Generated by Django 5.2 on 2025-05-24 07:56

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='dish_image',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='recipe_description',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='recipe_tutorial_url',
        ),
        migrations.CreateModel(
            name='SubDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(blank=True, null=True)),
                ('dish_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='dish_image/')),
                ('recipe_name', models.CharField(blank=True, null=True)),
                ('recipe_tutorial_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('diet_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan', to='app_diet_plan.dietplan')),
            ],
        ),
    ]
