# Generated by Django 5.2 on 2025-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdietplan',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subdietplan',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
