# Generated by Django 5.2 on 2025-05-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_image/'),
        ),
    ]
