# Generated by Django 5.2 on 2025-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0002_alter_dietplan_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='recipe_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='recipe_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='recipe_tutorial_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
