# Generated by Django 5.2 on 2025-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0002_dietplan_medication_alter_subdietplan_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdietplan',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], null=True),
        ),
    ]
