# Generated by Django 5.2 on 2025-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0002_remove_dietplan_dish_image_remove_dietplan_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdietplan',
            name='meal_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdietplan',
            name='recipe_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
