# Generated by Django 5.2 on 2025-06-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0003_alter_subdietplan_meal_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subdietplan',
            unique_together={('meal_type',)},
        ),
    ]
