# Generated by Django 5.2 on 2025-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0003_alter_dietplan_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='recipe_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='recipe_tutorial_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
