# Generated by Django 5.2 on 2025-06-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0003_dietplan_medication_alter_subdietplan_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdietplan',
            name='recipe_tutorial_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
