# Generated by Django 5.2 on 2025-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0003_alter_subdietplan_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
