# Generated by Django 5.2 on 2025-06-25 05:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0003_alter_subdietplan_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdietplan',
            name='dish_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='dish_image/'),
        ),
        migrations.AlterUniqueTogether(
            name='subdietplan',
            unique_together={('meal_type',)},
        ),
    ]
