# Generated by Django 5.2 on 2025-05-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0002_alter_dietplan_dish_image'),
        ('app_diet_plan', '0003_alter_subdietplan_meal_type_and_more'),
    ]

    operations = [
    ]
