# Generated by Django 5.2 on 2025-05-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0004_merge_20250523_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='dish_image',
        ),
    ]
