# Generated by Django 5.2 on 2025-06-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0004_alter_subdietplan_recipe_tutorial_url'),
        ('app_diet_plan', '0004_dietplan_medication'),
    ]

    operations = [
    ]
