# Generated by Django 5.2 on 2025-06-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diet_plan', '0004_alter_subdietplan_dish_image_and_more'),
        ('app_diet_plan', '0004_alter_subdietplan_unique_together'),
    ]

    operations = [
    ]
