from django.urls import path
from .views import (
    RegisterView,
    RegisterAdminView,
    LoginView,
    RefreshTokenView,
    LogoutView,
    ChangePasswordView,
    SendOTPView,
    VerifyOTPView,
    ResendOTPView,
    AddAccountHealthCareProviderView,
    ChangePasswordHealthCareProviderView,
    GetUsersView,
    GetUserView,
    GetUserRoleView,
    GetHealthCareProvidersView,
    EditProfileInPatientView,
    GetUserProfileInformationView,
    GetAllRegisteredProvidersView
)

urlpatterns = [
    path('send-otp/', SendOTPView.as_view(), name='send-otp'),
    path('verify-otp/', VerifyOTPView.as_view(), name='send-otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend-otp'),
    path('register/', RegisterView.as_view(), name='register'),
    path('account/register/', RegisterAdminView.as_view(), name='account-register'),
    path('login/', LoginView.as_view(), name='login'),
    path('refresh-token/', RefreshTokenView.as_view(), name='refresh-token'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('edit/profile/', EditProfileInPatientView.as_view(), name='edit-profile'),
    path('profile/', GetUserProfileInformationView.as_view(), name='profile'),
    path('provider/add-account/', AddAccountHealthCareProviderView.as_view(), name='provider-add-account'),
    path('provider/change-password/', ChangePasswordHealthCareProviderView.as_view(), name='provider-change-password'),
    path('get/patients/', GetUsersView.as_view(), name='get-patients'),
    path('get/patient/<str:pk>/', GetUserView.as_view(), name='get-user'),
    path('user/role/', GetUserRoleView.as_view(), name='get-user-role'),
    path('get/providers/', GetHealthCareProvidersView.as_view(), name='get-providers'),
    path('registered-providers/', GetAllRegisteredProvidersView.as_view(), name='get-registered-providers'),
]
