# Generated by Django 5.2 on 2025-05-08 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('7cd852a6-bca6-4986-8942-9418755696e3'), unique=True),
        ),
    ]
