# Generated by Django 5.2 on 2025-05-06 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('83007ba9-185c-4526-ba35-2b177974ba98'), unique=True),
        ),
    ]
