# Generated by Django 5.2 on 2025-05-18 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c3413c30-9093-4a74-87dc-ee022f4f3772'), unique=True),
        ),
    ]
