# Generated by Django 5.1.8 on 2025-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
