# Generated by Django 5.2 on 2025-05-16 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('40e0cea1-ad5d-47d0-b9ab-83dbcfe01d62'), unique=True),
        ),
    ]
