# Generated by Django 5.2 on 2025-05-06 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('app_authentication', '0002_user_status_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('21c1f3cb-12fb-409e-b0da-2197d2d218f3'), unique=True),
        ),
    ]
