# Generated by Django 5.2 on 2025-05-18 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0002_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('80ed4e22-758e-4d47-b4bb-8f357c58e0e4'), unique=True),
        ),
    ]
