# Generated by Django 5.2 on 2025-05-18 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0002_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('2c84939c-808b-4b98-b3d6-be4b37403378'), unique=True),
        ),
    ]
