# Generated by Django 5.2 on 2025-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
