# Generated by Django 5.2 on 2025-05-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_alter_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='suffix_name',
        ),
    ]
