<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-10 06:53
=======
# Generated by Django 5.2 on 2025-05-12 07:18
>>>>>>> 7cafe26a7ccd8850a6e4da09e66ba4120d01e72c

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('649d7f01-461d-4822-bc1a-68bd2df9f4f6'), unique=True),
=======
            field=models.UUIDField(default=uuid.UUID('fa01fbb3-2d97-4617-8888-26345d945ffd'), unique=True),
>>>>>>> 7cafe26a7ccd8850a6e4da09e66ba4120d01e72c
        ),
    ]
