# Generated by Django 5.2 on 2025-05-07 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('bc137987-2e59-46b2-8d51-70397f6752a5'), unique=True),
        ),
    ]
