# Generated by Django 5.2 on 2025-05-09 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('96f878e0-273f-4d34-a313-022ad44ef456'), unique=True),
        ),
    ]
