<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-10 10:23
=======
# Generated by Django 5.2 on 2025-05-12 07:18
>>>>>>> 7cafe26a7ccd8850a6e4da09e66ba4120d01e72c

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('29a909f1-af7d-4389-8391-d804bf2923b0'), unique=True),
=======
            field=models.UUIDField(default=uuid.uuid4, unique=True),
>>>>>>> 7cafe26a7ccd8850a6e4da09e66ba4120d01e72c
        ),
    ]
