# Generated by Django 5.2 on 2025-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('head nurse', 'Head Nurse'), ('caregiver', 'Caregiver')], max_length=20),
        ),
    ]
