# Generated by Django 5.2 on 2025-05-10 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0005_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('203a9502-c478-403a-a5c5-42484d350d0d'), unique=True),
        ),
    ]
