# Generated by Django 5.2 on 2025-05-01 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0005_alter_user_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('8ae6f805-9c39-4068-9ab7-2d1a411d8c8a'), unique=True),
        ),
    ]
