# Generated by Django 5.2 on 2025-05-13 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0005_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 13, 23, 16, 302912)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 13, 23, 16, 302949)),
        ),
    ]
