# Generated by Django 5.2 on 2025-05-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0002_user_status_alter_otp_otp_token'),
        ('app_authentication', '0005_alter_otp_otp_token'),
    ]

    operations = [
    ]
