# Generated by Django 5.2 on 2025-05-01 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('8a8e4db1-76fd-4919-a080-fc5d2033e8cf'), unique=True),
        ),
    ]
