# Generated by Django 5.2 on 2025-05-10 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('e01c2638-4a61-40c5-a7e7-696d6f270606'), unique=True),
        ),
    ]
