# Generated by Django 5.2 on 2025-06-02 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
