# Generated by Django 5.2 on 2025-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0007_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Admin', 'Admin'), ('Nurse', 'Nurse'), ('Head Nurse', 'Head Nurse'), ('Caregiver', 'Caregiver')], max_length=20),
        ),
    ]
