# Generated by Django 5.2 on 2025-06-02 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0007_alter_caregiver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_caregivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
