# Generated by Django 5.1.8 on 2025-05-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0002_alter_otp_otp_token'),
        ('app_authentication', '0007_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
    ]
