# Generated by Django 5.2 on 2025-05-10 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0007_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('2c8feec3-f1c9-4be3-90cd-dd4bc7a8c5d6'), unique=True),
        ),
    ]
