# Generated by Django 5.2 on 2025-05-02 04:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0008_remove_otp_email_remove_otp_password_otp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('56c5c916-41c5-4de7-bf9c-8ed9864cfc47'), unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='suffix_name',
            field=models.BooleanField(default=False),
        ),
    ]
