# Generated by Django 5.2 on 2025-05-10 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0008_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('1523a6b8-76b8-4b88-9536-2efdad386712'), unique=True),
        ),
    ]
