# Generated by Django 5.2 on 2025-05-11 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0009_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('2f081701-82a9-40ad-bb50-f5e6324875c2'), unique=True),
        ),
    ]
