# Generated by Django 5.2 on 2025-05-04 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0009_alter_otp_otp_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('0f99e478-90ba-455f-b199-0604ccb4dcea'), unique=True),
        ),
    ]
