# Generated by Django 5.2 on 2025-05-05 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0009_alter_otp_otp_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('54ad85d6-581c-4640-a81b-9e43dfc3e7a4'), unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('PROVIDER', 'Provider')], max_length=20),
        ),
    ]
