# Generated by Django 5.2 on 2025-05-05 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0010_user_address_alter_otp_otp_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('4c2bce36-a4cc-4d03-b8f5-c53bc36aba07'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('HEAD NURSE', 'Head Nurse'), ('PROVIDER', 'Provider'), ('CAREGIVER', 'Caregiver')], max_length=20),
        ),
    ]
