# Generated by Django 5.2 on 2025-05-11 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0010_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c81b0722-9f5a-4a97-adfe-b08c56a054fc'), unique=True),
        ),
    ]
