# Generated by Django 5.2 on 2025-05-04 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0010_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('ed0a4040-d800-4af1-8cce-ba676cc25032'), unique=True),
        ),
    ]
