# Generated by Django 5.2 on 2025-05-12 01:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0011_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('ca6fe690-e54f-48f3-b213-6dbbb0e585a0'), unique=True),
        ),
    ]
