# Generated by Django 5.2 on 2025-05-05 04:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0011_alter_otp_otp_token_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('6ef61cc6-bb0d-47b2-8518-a01b23d8242d'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('HEAD NURSE', 'Head Nurse  '), ('PROVIDER', 'Provider'), ('CAREGIVER', 'Caregiver')], max_length=20),
        ),
    ]
