# Generated by Django 5.2 on 2025-05-04 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0011_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('7a2f1f93-2336-4414-938f-c72b4328b7e8'), unique=True),
        ),
    ]
