# Generated by Django 5.2 on 2025-05-05 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0012_remove_user_address_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('18b3300b-34c2-402e-a64d-70b51e8a232a'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Admin', 'Admin'), ('Nurse', 'Nurse'), ('Head Nurse', 'Head Nurse'), ('Provider', 'Provider'), ('Caregiver', 'Caregiver')], max_length=20),
        ),
    ]
