# Generated by Django 5.2 on 2025-05-04 00:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0012_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('02499603-00f0-4e52-90b5-9e2b36abefd0'), unique=True),
        ),
    ]
