# Generated by Django 5.2 on 2025-05-12 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0012_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('2a857cf8-7560-409a-a11b-4dc7f5759d90'), unique=True),
        ),
    ]
