# Generated by Django 5.2 on 2025-05-04 00:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0013_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('60cad06d-f81c-43f3-942f-f3551897f372'), unique=True),
        ),
    ]
