# Generated by Django 5.2 on 2025-05-12 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0013_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('96597373-537b-466b-87ae-43dac91db4d4'), unique=True),
        ),
    ]
