# Generated by Django 5.2 on 2025-05-04 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0014_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('8eb176e8-e4bb-4235-a086-1c67075b501c'), unique=True),
        ),
    ]
