# Generated by Django 5.2 on 2025-05-13 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0014_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('d10948c6-5e64-4f04-ba4d-5e8fd6e4ae8e'), unique=True),
        ),
    ]
