# Generated by Django 5.2 on 2025-05-04 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0015_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('757cbd1f-44f5-4229-86f3-e5d47aa326b3'), unique=True),
        ),
    ]
