# Generated by Django 5.2 on 2025-05-13 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0015_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('7b01ccec-b373-4295-a3ea-6ddf34aa50f2'), unique=True),
        ),
    ]
