# Generated by Django 5.2 on 2025-05-13 01:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0016_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c0232c01-f8a2-4b22-8254-fffcc8f9a358'), unique=True),
        ),
    ]
