# Generated by Django 5.2 on 2025-05-04 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0016_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c233f80c-8b2b-4c1a-9750-a203a22feb40'), unique=True),
        ),
    ]
