# Generated by Django 5.2 on 2025-05-13 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0017_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('0700a4b6-a12c-4509-825b-cce96b262d47'), unique=True),
        ),
    ]
