# Generated by Django 5.2 on 2025-05-04 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0017_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('064513c9-a96c-4253-9b84-298de43e20e1'), unique=True),
        ),
    ]
