# Generated by Django 5.2 on 2025-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0013_alter_otp_otp_token_alter_user_role'),
        ('app_authentication', '0019_alter_otp_otp_token_alter_profile_picture'),
    ]

    operations = [
    ]
