# Generated by Django 5.2 on 2025-05-05 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0020_merge_20250505_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('a41f85bd-473a-429c-8a73-55fa4f21ba1b'), unique=True),
        ),
    ]
