# Generated by Django 5.2 on 2025-05-05 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0021_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('fc3858d5-7da3-400b-8d27-0e66b3736601'), unique=True),
        ),
    ]
