# Generated by Django 5.2 on 2025-05-05 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0022_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('6eb595ad-db76-4e9c-a6ac-dfd94299bfa3'), unique=True),
        ),
    ]
