# Generated by Django 5.2 on 2025-05-05 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0023_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('ec9a5113-07a9-4148-917e-6a21f6368894'), unique=True),
        ),
    ]
