# Generated by Django 5.2 on 2025-05-05 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0024_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('e3ea801c-ec09-4c1b-b1ee-57d5e5d59e66'), unique=True),
        ),
    ]
