# Generated by Django 5.2 on 2025-05-05 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0025_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('4dbd94a9-3ac7-4783-a849-0d6772257d90'), unique=True),
        ),
    ]
