# Generated by Django 5.2 on 2025-05-05 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0026_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('32ec3bc7-c256-4aca-be2a-43631adc9400'), unique=True),
        ),
    ]
