# Generated by Django 5.2 on 2025-05-05 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0027_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c27e58ee-94bc-41d2-8b0b-6157c38c3c5c'), unique=True),
        ),
    ]
