# Generated by Django 5.2 on 2025-05-05 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0028_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('73e9d541-d506-42ab-af3d-fa8ab31cf390'), unique=True),
        ),
    ]
