# Generated by Django 5.2 on 2025-05-05 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0030_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('c5f95808-6a44-4fc7-ab76-801186d19bca'), unique=True),
        ),
    ]
