# Generated by Django 5.2 on 2025-05-06 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0031_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('1763dc16-8c2a-4707-8275-c60474c2c758'), unique=True),
        ),
    ]
