# Generated by Django 5.1.8 on 2025-05-06 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0032_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('402faa81-a193-4005-b137-c716fc92e27e'), unique=True),
        ),
    ]
