# Generated by Django 5.1.8 on 2025-05-06 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0033_alter_otp_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_token',
            field=models.UUIDField(default=uuid.UUID('98b788cd-3574-4d83-9e20-0f407ca025ce'), unique=True),
        ),
    ]
