# Generated by Django 5.2 on 2025-05-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='assigned_machine',
        ),
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='assigned_provider',
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentassigned',
            name='assigned_machine',
            field=models.ManyToManyField(blank=True, to='app_appointment.machine'),
        ),
        migrations.AddField(
            model_name='appointmentassigned',
            name='assigned_provider',
            field=models.ManyToManyField(blank=True, to='app_appointment.provider'),
        ),
    ]
