# Generated by Django 5.2 on 2025-05-16 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Check-In', 'Check-In'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignedMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_machine', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_machine_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='app_appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_provider', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('assigned_provider_appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_assignments', to='app_appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='app_appointment.appointment')),
                ('assigned_machines', models.ManyToManyField(related_name='assigned_machine_appointments', to='app_appointment.assignedmachine')),
                ('assigned_providers', models.ManyToManyField(related_name='assigned_appointments', to='app_appointment.assignedprovider')),
            ],
        ),
        migrations.DeleteModel(
            name='AppointmentAssigned',
        ),
    ]
