# Generated by Django 5.2 on 2025-05-18 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='app_appointment.appointment'),
        ),
        migrations.AddField(
            model_name='assignedmachine',
            name='assigned_machine_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='app_appointment.appointment'),
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_machines',
            field=models.ManyToManyField(related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
        migrations.AddField(
            model_name='assignedprovider',
            name='assigned_provider',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedprovider',
            name='assigned_provider_appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_assignments', to='app_appointment.appointment'),
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_providers',
            field=models.ManyToManyField(related_name='assigned_appointments', to='app_appointment.assignedprovider'),
        ),
    ]
