# Generated by Django 5.2 on 2025-05-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedmachine',
            name='assigned_machine',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedmachine',
            name='assigned_machine_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machine_appointment', to='app_appointment.appointment'),
        ),
    ]
