# Generated by Django 5.2 on 2025-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedmachine',
            name='assigned_machine',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
