# Generated by Django 5.2 on 2025-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0002_remove_appointmentassigned_assigned_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='assigned_machine',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='assigned_provider',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AddField(
            model_name='appointmentassigned',
            name='assigned_machine',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AddField(
            model_name='appointmentassigned',
            name='assigned_provider',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
