# Generated by Django 5.2 on 2025-05-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0003_alter_assignedmachine_assigned_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_machines',
        ),
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_providers',
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_provider_appointment', to='app_appointment.assignedprovider'),
        ),
        migrations.AlterField(
            model_name='assignedprovider',
            name='assigned_provider_appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_provider_appointment', to='app_appointment.appointment'),
        ),
    ]
