# Generated by Django 5.2 on 2025-05-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0003_remove_appointmentassigned_assigned_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='assigned_machine',
        ),
    ]
