# Generated by Django 5.2 on 2025-05-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0004_remove_appointmentassigned_assigned_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentassigned',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_appointment.appointment'),
        ),
    ]
