# Generated by Django 5.2 on 2025-05-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0004_remove_assignedappointment_assigned_machines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedprovider',
            name='assigned_provider_appointments',
        ),
        migrations.AddField(
            model_name='assignedprovider',
            name='assigned_patient_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patient_appointment', to='app_appointment.appointment'),
        ),
    ]
