# Generated by Django 5.2 on 2025-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0006_alter_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointmentassigned',
            name='updated_at',
        ),
    ]
