# Generated by Django 5.2 on 2025-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0007_remove_appointmentassigned_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentassigned',
            name='assigned_machine',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
