# Generated by Django 5.2 on 2025-05-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0008_appointmentassigned_assigned_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_provider', models.JSONField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_appointment.appointment')),
                ('assigned_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='app_appointment.assignedmachine')),
            ],
        ),
        migrations.DeleteModel(
            name='AppointmentAssigned',
        ),
    ]
