# Generated by Django 5.2 on 2025-05-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0009_assignedmachine_assignedappointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedmachine',
            old_name='machine',
            new_name='assigned_machine',
        ),
    ]
