# Generated by Django 5.2 on 2025-05-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0010_rename_machine_assignedmachine_assigned_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedappointment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_appointment.appointment'),
        ),
    ]
