# Generated by Django 5.1.8 on 2025-05-06 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0011_alter_assignedappointment_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_provider',
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_providers',
            field=models.ManyToManyField(related_name='provider_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedappointment',
            name='assigned_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
    ]
