# Generated by Django 5.1.8 on 2025-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0012_remove_assignedappointment_assigned_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_providers',
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_provider',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
