# Generated by Django 5.2 on 2025-05-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0014_remove_appointment_date_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_provider', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignedappointment',
            name='assigned_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
        migrations.AlterField(
            model_name='assignedappointment',
            name='assigned_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_provider_appointments', to='app_appointment.assignedprovider'),
        ),
    ]
