# Generated by Django 5.2 on 2025-05-10 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0016_alter_assignedprovider_assigned_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedappointment',
            name='assigned_machine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
        migrations.AlterField(
            model_name='assignedprovider',
            name='assigned_provider',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
