# Generated by Django 5.2 on 2025-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0017_alter_assignedappointment_assigned_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_machine',
        ),
        migrations.RemoveField(
            model_name='assignedappointment',
            name='assigned_provider',
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_machine',
            field=models.ManyToManyField(related_name='assigned_machine_appointments', to='app_appointment.assignedmachine'),
        ),
        migrations.AddField(
            model_name='assignedappointment',
            name='assigned_provider',
            field=models.ManyToManyField(related_name='assigned_provider_appointments', to='app_appointment.assignedprovider'),
        ),
    ]
