# Generated by Django 5.2 on 2025-05-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0018_remove_assignedappointment_assigned_machine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedappointment',
            old_name='assigned_machine',
            new_name='assigned_machines',
        ),
        migrations.RenameField(
            model_name='assignedappointment',
            old_name='assigned_provider',
            new_name='assigned_providers',
        ),
    ]
