# Generated by Django 5.2 on 2025-05-11 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0019_rename_assigned_machine_assignedappointment_assigned_machines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedappointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_appointment.appointment'),
        ),
    ]
