# Generated by Django 5.2 on 2025-05-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0020_alter_assignedappointment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedappointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='app_appointment.appointment'),
        ),
    ]
