# Generated by Django 5.2 on 2025-05-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0021_alter_assignedappointment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Check-In', 'Check-In'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20),
        ),
    ]
