# Generated by Django 5.2 on 2025-05-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0023_alter_assignedprovider_assigned_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprovider',
            name='assigned_provider_appointments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_assignments', to='app_appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='assignedappointment',
            name='assigned_providers',
            field=models.ManyToManyField(related_name='assigned_appointments', to='app_appointment.assignedprovider'),
        ),
    ]
