# Generated by Django 5.2 on 2025-05-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_appointment', '0024_assignedprovider_assigned_provider_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedmachine',
            name='assigned_machine_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='app_appointment.appointment'),
        ),
    ]
