# Generated by Django 5.2 on 2025-05-13 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to=settings.AUTH_USER_MODEL),
        ),
    ]
