# Generated by Django 5.2 on 2025-05-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0002_remove_treatment_appointment_treatment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstype',
            name='type',
            field=models.JSONField(default=list),
        ),
    ]
