# Generated by Django 5.2 on 2025-05-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0003_alter_accesstype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pulse_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pulse_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
