# Generated by Django 5.2 on 2025-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0004_alter_prescription_pulse_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='respiratory_rate_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='respiratory_rate_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
