# Generated by Django 5.2 on 2025-05-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0005_alter_prescription_respiratory_rate_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreatmentDetails',
            new_name='TreatmentDetail',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='saturation_percentage_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='saturation_percentage_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
