# Generated by Django 5.2 on 2025-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0006_rename_treatmentdetails_treatmentdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='rbs_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rbs_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentdetail',
            name='dialysis_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentdetail',
            name='machine_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
