# Generated by Django 5.2 on 2025-05-13 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0008_alter_treatment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='access_type',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='left_via',
            field=models.CharField(blank=True, choices=[('Ambulatory', 'Ambulatory'), ('Stretcher', 'Stretcher'), ('Wheelchair', 'Wheelchair')], null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='time_ended',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='time_started',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostDialysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(blank=True, null=True)),
                ('respiratroy', models.CharField(blank=True, null=True)),
                ('cardiac', models.CharField(blank=True, null=True)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_post_dialysis', to='app_treatment.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PreDialysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(blank=True, null=True)),
                ('respiratroy', models.CharField(blank=True, null=True)),
                ('cardiac', models.CharField(blank=True, null=True)),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_pre_dialysis', to='app_treatment.treatment')),
            ],
        ),
    ]
