# Generated by Django 5.2 on 2025-05-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_treatment', '0009_accesstype_access_type_treatmentdetail_left_via_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdialysis',
            old_name='respiratroy',
            new_name='respiratory',
        ),
        migrations.RenameField(
            model_name='predialysis',
            old_name='respiratroy',
            new_name='respiratory',
        ),
    ]
