services:
  - type: web
    name: kidneycare-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT kidney.asgi:application --verbosity 3
    websocketSupport: true  # 🔥 This enables WebSocket support explicitly
    envVars:
      - key: API_KEY
        value: 578212266594366
      - key: API_SECRET
        value: XVujwdKnUQ3D3w0QQiKPTZgDgk8
      - key: CLOUD_NAME
        value: ddidkcn9e
      - key: CLOUDINARY_URL
        value: cloudinary://578212266594366:XVujwdKnUQ3D3w0QQiKPTZgDgk8@ddidkcn9e
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_3AbhXf5QjZRI@ep-autumn-meadow-a1esuoug-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: kidney.settings
      - key: EMAIL_HOST_PASSWORD
        value: rpstswnbgslhtvtu
      - key: EMAIL_HOST_USER
        value: 19201.bautista.martin.s0010@gmail.com
      - key: REDIS_URL
        value: redis://default:gCFK8c8QYhGmGssIqfFXDqaqybD6f6uR@redis-12945.c299.asia-northeast1-1.gce.redns.redis-cloud.com:12945
      - key: SECRET_KEY
        value: django-insecure-#b11%rn9s2bkt6cq=4n=v$z)5^j_%bdq1vj57ew6)+-i4nswok