# Generated by Django 5.2 on 2025-05-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
