# Generated by Django 5.2 on 2025-05-22 01:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0002_alter_newsevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newseventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news_event_image/'),
        ),
    ]
