# Generated by Django 5.2 on 2025-05-04 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0003_alter_newsevent_date_alter_newsevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(default=datetime.date, null=True),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='time',
            field=models.TimeField(default=datetime.time, null=True),
        ),
    ]
