# Generated by Django 5.2 on 2025-05-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0006_alter_newsevent_date_alter_newsevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
