# Generated by Django 5.2 on 2025-05-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0007_alter_newsevent_date_alter_newsevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
