# Generated by Django 5.2 on 2025-05-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0008_alter_newsevent_date_alter_newsevent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsevent',
            name='images',
        ),
        migrations.CreateModel(
            name='NewsEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/news_event_image/')),
                ('news_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_news_event.newsevent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
