# Generated by Django 5.1.8 on 2025-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_event', '0009_remove_newsevent_images_newseventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
