# Generated by Django 5.2 on 2025-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_message_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Sent', 'sent'), ('Delivered', 'delivered'), ('Read', 'read')], default='Sent', max_length=20),
        ),
    ]
