# Generated by Django 5.2 on 2025-06-03 05:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Sent', 'sent'), ('Delivered', 'delivered'), ('Read', 'read')], default='Sent', max_length=20),
        ),
    ]
