# Generated by Django 5.2 on 2025-06-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_alter_message_status'),
        ('app_chat', '0003_message_image_alter_message_status'),
    ]

    operations = [
    ]
